# 搜索关键词
keyWords:
  - 浴霸
  - 吸顶灯
  - 鸡蛋
  - 红包

# 最低评论数
lowCommentNum: 1
# 最低值率
lowWorthyNum: 6
# 满意商品数量
satisfyNum: 5
# 过滤词
filterWords:
  - "过期"
  - "售罄"

# 定时任务多长执行一次 单位秒 默认 3个小时
tickTime: 3
# 钉钉token
dingdingToken: "9e4044952fe5c599afed3815ccaa387c650fd07bda96512648acfceb1b202ada"

# 签到时间(默认早上8:30)
cron: "0 10 10 ? * *"

telegramBotToken: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"  # 从 @BotFather 获取
telegramChatId: "-1001234567890"  # 个人 chat id 或 群 id（群通常为 -100...）
